name: update-version
on: [push, pull_request]

jobs:
  update-version:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/auto-roll-node-package-version'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - run: npm install
      - name: Setup GIT
        run: |
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git config user.name "$GITHUB_ACTOR"
      - run: |
          npm version patch -m "ci: Patch to %s"
          git push
